wiremock:
  server:
    port: 9999

server:
  shutdown: immediate

spring:
  main:
    allow-bean-definition-overriding: true

uri:
  authenticator:  http://localhost:${wiremock.server.port}
  currency-manager: http://localhost:8080
  group-manager: http://localhost:8080
  expense-manager: http://localhost:8080
  attachment-store: http://localhost:8080
  user-details-manager: http://localhost:8080
  finance-adapter: http://localhost:8080
  payment-manager: http://localhost:8080
  report-creator: http://localhost:8080

