token:
  secret-key: 8692tg18dEq2twmv48AtiKWp3Qo/2nw6/tU6Rzttm9Q=

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      httpclient:
        response-timeout: 10s
        connect-timeout: 5000
        pool:
          max-idle-time: 10m
          max-life-time: 30m
          max-connections: 500

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

retry:
  times: 3
